(() => {
  'use strict';
  const KEY='lightpath-language';
  const PT={
    'meta.title':'LightPath Tecnologia — Do gargalo ao resultado','meta.description':'LightPath Tecnologia conecta dados, software, IA, automação e growth systems para transformar gargalos em receita, eficiência e escala.','meta.ogTitle':'LightPath Tecnologia — Do gargalo ao resultado','meta.ogDescription':'Do clique ao caixa. Do dado à decisão. Da rotina ao sistema. Da IA ao produto.',
    'nav.aria':'Navegação principal','nav.open':'Abrir menu','nav.close':'Fechar menu','nav.capabilities':'Capabilities','nav.impact':'Impacto','nav.method':'Como atuamos','nav.presentation':'Apresentação','nav.cta':'Encontrar oportunidade','lang.aria':'Alternar idioma',
    'hero.eyebrow':'DADOS · IA · AUTOMAÇÃO · GROWTH SYSTEMS','hero.line1':'MENOS OPERAÇÃO MANUAL.','hero.line2':'MAIS INTELIGÊNCIA.','hero.line3':'MAIS ESCALA.','hero.sub':'Conectamos dados, sistemas, IA e funis comerciais para reduzir atrito, melhorar conversão e criar operações que crescem com controle.','hero.cta':'Encontrar meu próximo ganho','hero.demo':'Ver apresentação interativa','hero.orbitKicker':'LIGHTPATH / VALUE ENGINE','hero.orbitTitle':'Gargalo → Sistema → Resultado',
    'pathways.kicker':'ONDE A LIGHTPATH ENTRA','pathways.title':'DO GARGALO AO <em>RESULTADO.</em>','pathways.copy':'Quatro caminhos simples explicam quase tudo que fazemos. A tecnologia aparece depois — quando sabemos qual resultado precisa mudar.','pathways.p1.kicker':'RECEITA','pathways.p1.title':'DO CLIQUE<br>AO CAIXA.','pathways.p1.copy':'Mídia, landing, checkout, tracking, CRM e retenção conectados.','pathways.p2.kicker':'DECISÃO','pathways.p2.title':'DO DADO<br>À DECISÃO.','pathways.p2.copy':'Integração, pipelines, BI e analytics para agir mais rápido.','pathways.p3.kicker':'OPERAÇÃO','pathways.p3.title':'DA ROTINA<br>AO SISTEMA.','pathways.p3.copy':'Automação, APIs, integrações e software tirando trabalho manual do caminho.','pathways.p4.kicker':'INOVAÇÃO','pathways.p4.title':'DA IA<br>AO PRODUTO.','pathways.p4.copy':'Agentes, RAG, copilots e aplicações de IA conectadas ao trabalho real.',
    'cap.kicker':'CAPABILITIES','cap.title':'A MENOR ARQUITETURA<br>QUE <em>MOVE O NEGÓCIO.</em>','cap.copy':'Podemos melhorar uma peça ou conectar a cadeia inteira. O ponto de partida é sempre o gargalo — não a tecnologia da moda.','cap.data.title':'Dados confiáveis antes da decisão.','cap.data.copy':'Pipelines, lakehouse, integrações, qualidade e observabilidade.','cap.ai.title':'IA executando trabalho real.','cap.ai.copy':'Agentes, RAG, copilots, classificação, extração e produtos multimodais.','cap.auto.title':'Rotina vira sistema.','cap.auto.copy':'APIs, eventos, webhooks, filas, integrações e processos observáveis.','cap.growth.title':'Do anúncio à receita real.','cap.growth.copy':'Mídia, CRO, landing, checkout, tracking, attribution, CRM e lifecycle.','cap.analytics.title':'Dado que aponta o próximo movimento.','cap.analytics.copy':'BI, Data Science, forecast, segmentação e otimização operacional.',
    'system.kicker':'CONTROL LAYER','system.title':'NÃO ENTREGAMOS<br>UMA DEMO.<br><em>ENTREGAMOS FLUXO.</em>','system.copy':'Sources, dados, automação, IA e decisão funcionando como uma cadeia mensurável — com segurança, governança e observabilidade.','system.aria':'Fluxo de arquitetura','system.rail1':'segurança','system.rail2':'observabilidade','system.rail3':'governança',
    'growth.kicker':'GROWTH SYSTEMS','growth.title':'R$1 ENTRA AQUI.<br><em>QUANTO CHEGA NO CAIXA?</em>','growth.copy':'Você investe para trazer uma pessoa. Nós seguimos o caminho até a venda e a retenção para descobrir onde o valor está vazando — sem adivinhar.','growth.label':'LIGHTPATH / REVENUE PATH','growth.question':'R$1 investido → ? receita real','growth.aria':'Funil comercial integrado','growth.s1.title':'ANÚNCIO','growth.s1.copy':'Quem chegou?','growth.s2.copy':'Quem avançou?','growth.s3.copy':'Quem tentou comprar?','growth.s4.title':'PAGAMENTO','growth.s4.copy':'Qual venda aconteceu?','growth.s5.title':'RETENÇÃO','growth.s5.copy':'Quanto valor ficou?','growth.insightKicker':'O QUE A LIGHTPATH CONECTA','growth.insightTitle':'Mídia + produto + tracking + verdade comercial.','growth.insightCopy':'UTM, event_id, CAPI, GA4, checkout, pedido, CRM e lifecycle voltam a contar a mesma história.',
    'impact.kicker':'BUSINESS IMPACT','impact.title':'ANTES → SISTEMA → <em>RESULTADO.</em>','impact.copy':'Experiência técnica real em produção, traduzida para o que o negócio sente: capacidade, custo, velocidade e eficiência.','impact.note':'<strong>Transparência:</strong> os cases representam experiência técnica real em sistemas e produtos de produção e não implicam que todos tenham sido contratados originalmente sob a marca LightPath Tecnologia.','common.before':'ANTES','common.system':'SISTEMA','common.after':'DEPOIS',
    'case1.title':'Escalar processamento sem transformar infraestrutura em gargalo.','case1.before':'Grandes volumes e janelas críticas pressionando pipelines distribuídos.','case1.after':'processados por mês, com runtime até 20% menor.','case2.title':'Retirar pessoas da rotina repetitiva sem perder controle.','case2.before':'Execuções recorrentes dependentes de intervenção e memória.','case2.system':'Orquestração, scheduling, retries, alertas e observabilidade.','case2.after':'dos fluxos recorrentes automatizados no contexto operado.','case3.title':'Transformar coleta manual em serviço reutilizável.','case3.before':'Coleta e movimentação manual de dados entre fontes e consumidores.','case3.system':'FastAPI, integrações e camada programática de ingestão.','case3.after':'de esforço manual associado ao processo de ingestão.','case4.title':'Fazer a gestão enxergar antes — e agir mais rápido.','case4.before':'Informação dispersa e consolidação manual atrasando decisões.','case4.system':'SQL, automação, BI e camada analítica orientada à gestão.','case4.after':'de eficiência operacional no contexto de gestão e planejamento.',
    'proof.kicker':'ENGENHARIA COM PROVA','proof.title':'NÚMEROS QUE VIRAM<br><em>CAPACIDADE.</em>','proof.copy':'Não mostramos métricas como decoração. Cada uma representa trabalho manual removido, capacidade criada ou informação chegando mais perto da decisão.','proof.m1':'processados / mês','proof.m2':'fluxos recorrentes automatizados','proof.m3':'esforço manual em ingestão','proof.m4':'eficiência operacional','proof.projectTitle':'IA multimodal do dado ao produto.','proof.projectCopy':'Curadoria de dados, APIs, outputs estruturados, autenticação, tracking e operação de uma aplicação AI-assisted multilíngue.',
    'method.kicker':'COMO ATUAMOS','method.title':'PRIMEIRO O IMPACTO.<br><em>DEPOIS A TECNOLOGIA.</em>','method.copy':'Cada projeto começa por uma pergunta: qual mudança mensurável justificaria construir essa solução?','method.s1.kicker':'DIAGNÓSTICO','method.s1.title':'Mapeamos onde o valor está travado.','method.s1.copy':'Processos, dados, decisões, tempo, retrabalho, custo e risco.','method.s1.out':'Mapa de oportunidades','method.s2.kicker':'DESENHO','method.s2.title':'Escolhemos a menor arquitetura que resolve.','method.s2.copy':'Solução, integrações, dados, segurança e métrica de sucesso.','method.s2.out':'Arquitetura + plano','method.s3.kicker':'IMPLEMENTAÇÃO','method.s3.title':'Construímos para uso real, não para demo.','method.s3.copy':'Software, integrações, modelos, testes e observabilidade até produção.','method.s3.out':'Solução em produção','method.s4.kicker':'OTIMIZAÇÃO','method.s4.title':'Medimos o que mudou e ampliamos o ganho.','method.s4.copy':'Tempo poupado, conversão, custo, capacidade, qualidade ou produtividade.','method.s4.out':'ROI + próximo ganho',
    'diagnostic.title':'ONDE ESTÁ O SEU<br><em>PRÓXIMO GANHO?</em>','diagnostic.copy':'Escolha o sinal que mais incomoda. A LightPath traduz o sintoma em um primeiro vetor de solução e nas métricas que precisam provar valor.','diagnostic.o1':'TEMPO','diagnostic.o2':'CUSTO','diagnostic.o3':'RECEITA','diagnostic.o4':'RISCO','diagnostic.o5':'DECISÃO','diagnostic.hypothesis':'PRIMEIRA HIPÓTESE','diagnostic.defaultTitle':'Automação de processo','diagnostic.defaultCopy':'Mapeamos esperas, handoffs e tarefas repetitivas para reduzir lead time sem criar outra camada de operação.','diagnostic.kpiHours':'horas recuperadas','diagnostic.cta':'Transformar em diagnóstico',
    'scan.tempo.title':'Automação de processo','scan.tempo.copy':'Mapeamos esperas, handoffs e tarefas repetitivas para reduzir lead time sem criar outra camada de operação.','scan.tempo.kpis':'lead time|horas recuperadas|SLA','scan.custo.title':'Data + automação orientados a margem','scan.custo.copy':'Identificamos onde pessoas, compute ou retrabalho crescem mais rápido que o resultado e desenhamos a menor arquitetura que quebra essa relação.','scan.custo.kpis':'custo / transação|retrabalho|runtime','scan.receita.title':'Growth System / funil comercial','scan.receita.copy':'Seguimos a jornada do anúncio ao pagamento para descobrir onde conversão e receita estão vazando — e qual teste deve vir primeiro.','scan.receita.kpis':'CAC|conversão|receita por visita','scan.risco.title':'Observabilidade + guardrails','scan.risco.copy':'Transformamos dependência de memória, erro manual e baixa rastreabilidade em controles, logs, validações e supervisão.','scan.risco.kpis':'erro|incidentes|rastreabilidade','scan.decisao.title':'Analytics + IA aplicada','scan.decisao.copy':'Reduzimos a distância entre o evento e a decisão com dados confiáveis, alertas, modelos e interfaces orientadas ao próximo movimento.','scan.decisao.kpis':'latência decisória|qualidade|forecast',
    'final.title':'QUAL GARGALO<br>MERECE SER <em>REMOVIDO PRIMEIRO?</em>','final.copy':'Você traz o gargalo. Nós ajudamos a transformar em hipótese de impacto, arquitetura e próximos passos.','final.email':'Falar com a LightPath','final.presentation':'Abrir apresentação','footer.copy':'Dados, IA, automação e growth systems para transformar atrito em alavancagem.'
  };
  const EN={
    'meta.title':'LightPath Technology — From bottleneck to outcome','meta.description':'LightPath connects data, software, AI, automation and growth systems to turn bottlenecks into revenue, efficiency and scale.','meta.ogTitle':'LightPath Technology — From bottleneck to outcome','meta.ogDescription':'From click to cash. From data to decision. From routine to system. From AI to product.',
    'nav.aria':'Main navigation','nav.open':'Open menu','nav.close':'Close menu','nav.capabilities':'Capabilities','nav.impact':'Impact','nav.method':'How we work','nav.presentation':'Presentation','nav.cta':'Find opportunity','lang.aria':'Switch language',
    'hero.eyebrow':'DATA · AI · AUTOMATION · GROWTH SYSTEMS','hero.line1':'LESS MANUAL WORK.','hero.line2':'MORE INTELLIGENCE.','hero.line3':'MORE SCALE.','hero.sub':'We connect data, systems, AI and commercial funnels to reduce friction, improve conversion and build operations that scale with control.','hero.cta':'Find my next gain','hero.demo':'View interactive presentation','hero.orbitKicker':'LIGHTPATH / VALUE ENGINE','hero.orbitTitle':'Bottleneck → System → Outcome',
    'pathways.kicker':'WHERE LIGHTPATH ENTERS','pathways.title':'FROM BOTTLENECK TO <em>OUTCOME.</em>','pathways.copy':'Four simple paths explain almost everything we do. Technology comes second — after we know which outcome must change.','pathways.p1.kicker':'REVENUE','pathways.p1.title':'FROM CLICK<br>TO CASH.','pathways.p1.copy':'Media, landing, checkout, tracking, CRM and retention connected.','pathways.p2.kicker':'DECISION','pathways.p2.title':'FROM DATA<br>TO DECISION.','pathways.p2.copy':'Integration, pipelines, BI and analytics to act faster.','pathways.p3.kicker':'OPERATIONS','pathways.p3.title':'FROM ROUTINE<br>TO SYSTEM.','pathways.p3.copy':'Automation, APIs, integrations and software removing manual work from the path.','pathways.p4.kicker':'INNOVATION','pathways.p4.title':'FROM AI<br>TO PRODUCT.','pathways.p4.copy':'Agents, RAG, copilots and AI applications connected to real work.',
    'cap.kicker':'CAPABILITIES','cap.title':'THE SMALLEST ARCHITECTURE<br>THAT <em>MOVES THE BUSINESS.</em>','cap.copy':'We can improve one piece or connect the entire chain. The starting point is always the bottleneck — not fashionable technology.','cap.data.title':'Reliable data before the decision.','cap.data.copy':'Pipelines, lakehouse, integrations, quality and observability.','cap.ai.title':'AI doing real work.','cap.ai.copy':'Agents, RAG, copilots, classification, extraction and multimodal products.','cap.auto.title':'Routine becomes system.','cap.auto.copy':'APIs, events, webhooks, queues, integrations and observable processes.','cap.growth.title':'From ad to real revenue.','cap.growth.copy':'Media, CRO, landing, checkout, tracking, attribution, CRM and lifecycle.','cap.analytics.title':'Data that points to the next move.','cap.analytics.copy':'BI, Data Science, forecasting, segmentation and operational optimization.',
    'system.kicker':'CONTROL LAYER','system.title':'WE DO NOT DELIVER<br>A DEMO.<br><em>WE DELIVER FLOW.</em>','system.copy':'Sources, data, automation, AI and decision working as a measurable chain — with security, governance and observability.','system.aria':'Architecture flow','system.rail1':'security','system.rail2':'observability','system.rail3':'governance',
    'growth.kicker':'GROWTH SYSTEMS','growth.title':'R$1 ENTERS HERE.<br><em>HOW MUCH REACHES CASH?</em>','growth.copy':'You invest to bring someone in. We follow the path through sale and retention to discover where value leaks — without guessing.','growth.label':'LIGHTPATH / REVENUE PATH','growth.question':'R$1 invested → ? real revenue','growth.aria':'Integrated commercial funnel','growth.s1.title':'AD','growth.s1.copy':'Who arrived?','growth.s2.copy':'Who moved forward?','growth.s3.copy':'Who tried to buy?','growth.s4.title':'PAYMENT','growth.s4.copy':'Which sale actually happened?','growth.s5.title':'RETENTION','growth.s5.copy':'How much value stayed?','growth.insightKicker':'WHAT LIGHTPATH CONNECTS','growth.insightTitle':'Media + product + tracking + commercial truth.','growth.insightCopy':'UTM, event_id, CAPI, GA4, checkout, order, CRM and lifecycle return to telling the same story.',
    'impact.kicker':'BUSINESS IMPACT','impact.title':'BEFORE → SYSTEM → <em>OUTCOME.</em>','impact.copy':'Real production engineering experience translated into what the business feels: capacity, cost, speed and efficiency.','impact.note':'<strong>Transparency:</strong> the cases represent real technical experience in production systems and products and do not imply they were all originally contracted under the LightPath Tecnologia brand.','common.before':'BEFORE','common.system':'SYSTEM','common.after':'AFTER',
    'case1.title':'Scale processing without turning infrastructure into the bottleneck.','case1.before':'Large volumes and critical windows pressuring distributed pipelines.','case1.after':'processed per month, with runtime up to 20% lower.','case2.title':'Remove people from repetitive operations without losing control.','case2.before':'Recurring executions dependent on intervention and memory.','case2.system':'Orchestration, scheduling, retries, alerts and observability.','case2.after':'of recurring flows automated in the operated context.','case3.title':'Turn manual collection into a reusable service.','case3.before':'Manual collection and movement of data between sources and consumers.','case3.system':'FastAPI, integrations and a programmatic ingestion layer.','case3.after':'less manual effort associated with the ingestion process.','case4.title':'Help management see earlier — and act faster.','case4.before':'Scattered information and manual consolidation delaying decisions.','case4.system':'SQL, automation, BI and an analytics layer oriented to management.','case4.after':'operational efficiency in the management and planning context.',
    'proof.kicker':'ENGINEERING WITH PROOF','proof.title':'NUMBERS THAT BECOME<br><em>CAPACITY.</em>','proof.copy':'We do not use metrics as decoration. Each one represents manual work removed, capacity created or information moving closer to the decision.','proof.m1':'processed / month','proof.m2':'recurring flows automated','proof.m3':'manual ingestion effort','proof.m4':'operational efficiency','proof.projectTitle':'Multimodal AI from data to product.','proof.projectCopy':'Data curation, APIs, structured outputs, authentication, tracking and operation of a multilingual AI-assisted application.',
    'method.kicker':'HOW WE WORK','method.title':'IMPACT FIRST.<br><em>TECHNOLOGY SECOND.</em>','method.copy':'Every project starts with one question: what measurable change would justify building this solution?','method.s1.kicker':'DIAGNOSIS','method.s1.title':'We map where value is stuck.','method.s1.copy':'Processes, data, decisions, time, rework, cost and risk.','method.s1.out':'Opportunity map','method.s2.kicker':'DESIGN','method.s2.title':'We choose the smallest architecture that solves it.','method.s2.copy':'Solution, integrations, data, security and success metric.','method.s2.out':'Architecture + plan','method.s3.kicker':'IMPLEMENTATION','method.s3.title':'We build for real use, not a demo.','method.s3.copy':'Software, integrations, models, tests and observability through production.','method.s3.out':'Production solution','method.s4.kicker':'OPTIMIZATION','method.s4.title':'We measure what changed and expand the gain.','method.s4.copy':'Time saved, conversion, cost, capacity, quality or productivity.','method.s4.out':'ROI + next gain',
    'diagnostic.title':'WHERE IS YOUR<br><em>NEXT GAIN?</em>','diagnostic.copy':'Choose the signal that hurts most. LightPath translates the symptom into a first solution vector and the metrics that need to prove value.','diagnostic.o1':'TIME','diagnostic.o2':'COST','diagnostic.o3':'REVENUE','diagnostic.o4':'RISK','diagnostic.o5':'DECISION','diagnostic.hypothesis':'FIRST HYPOTHESIS','diagnostic.defaultTitle':'Process automation','diagnostic.defaultCopy':'We map waits, handoffs and repetitive tasks to reduce lead time without creating another operational layer.','diagnostic.kpiHours':'hours recovered','diagnostic.cta':'Turn into a diagnosis',
    'scan.tempo.title':'Process automation','scan.tempo.copy':'We map waits, handoffs and repetitive tasks to reduce lead time without creating another operational layer.','scan.tempo.kpis':'lead time|hours recovered|SLA','scan.custo.title':'Data + automation oriented to margin','scan.custo.copy':'We identify where people, compute or rework grow faster than outcomes and design the smallest architecture that breaks that relationship.','scan.custo.kpis':'cost / transaction|rework|runtime','scan.receita.title':'Growth System / commercial funnel','scan.receita.copy':'We follow the journey from ad to payment to discover where conversion and revenue leak — and which test should come first.','scan.receita.kpis':'CAC|conversion|revenue per visit','scan.risco.title':'Observability + guardrails','scan.risco.copy':'We turn dependency on memory, manual error and low traceability into controls, logs, validations and supervision.','scan.risco.kpis':'error|incidents|traceability','scan.decisao.title':'Analytics + applied AI','scan.decisao.copy':'We reduce the distance between event and decision with reliable data, alerts, models and interfaces oriented to the next move.','scan.decisao.kpis':'decision latency|quality|forecast',
    'final.title':'WHICH BOTTLENECK<br>DESERVES TO BE <em>REMOVED FIRST?</em>','final.copy':'You bring the bottleneck. We help turn it into an impact hypothesis, architecture and next steps.','final.email':'Talk to LightPath','final.presentation':'Open presentation','footer.copy':'Data, AI, automation and growth systems to turn friction into leverage.'
  };
  const dict={pt:PT,en:EN};
  let lang=(localStorage.getItem(KEY)==='en')?'en':'pt';
  const t=(key,l=lang)=>dict[l]?.[key]??dict.pt[key]??key;
  function apply(root=document){
    document.documentElement.lang=lang==='en'?'en':'pt-BR';
    root.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});
    root.querySelectorAll('[data-i18n-html]').forEach(el=>{el.innerHTML=t(el.dataset.i18nHtml)});
    root.querySelectorAll('[data-i18n-attr]').forEach(el=>{
      el.dataset.i18nAttr.split(';').forEach(pair=>{const [attr,key]=pair.split(':');if(attr&&key)el.setAttribute(attr,t(key));});
    });
    document.querySelectorAll('[data-lang-toggle]').forEach(btn=>btn.dataset.lang=lang);
    const title=t('meta.title'); if(title) document.title=title;
    window.dispatchEvent(new CustomEvent('lightpath:languagechange',{detail:{lang}}));
  }
  function set(next){lang=next==='en'?'en':'pt';localStorage.setItem(KEY,lang);apply();}
  window.LightPathI18n={t,set,apply,get lang(){return lang;}};
  document.addEventListener('DOMContentLoaded',()=>{
    apply();
    document.querySelectorAll('[data-lang-toggle]').forEach(btn=>btn.addEventListener('click',()=>set(lang==='pt'?'en':'pt')));
  });
})();
