(() => {
  'use strict';
  const KEY='lightpath-language';
  const D={
    pt:{
      'hero.kicker':'LIGHTPATH / INTERACTIVE STORY','hero.a':'Seu próximo ganho está','hero.b':'escondido no processo.','hero.copy':'Do clique ao caixa. Do dado à decisão. Da rotina ao sistema. Da IA ao produto.','hero.cta':'Começar',
      'impact.kicker':'01 / IMPACTO','impact.a':'Tecnologia não é o produto.','impact.b':'O impacto é.','impact.copy':'Escolha o resultado que precisa mover.','impact.core':'IMPACTO','impact.sub':'mensurável','impact.cost':'REDUZIR CUSTO','impact.speed':'ACELERAR DECISÃO','impact.scale':'CRIAR ESCALA',
      'diagnosis.kicker':'02 / DIAGNÓSTICO','diagnosis.a':'Onde o valor','diagnosis.b':'trava?','diagnosis.copy':'Escolha o gargalo. Nós mostramos o primeiro vetor.','diagnosis.data':'DADOS DISPERSOS','diagnosis.manual':'PROCESSO MANUAL','diagnosis.delay':'DECISÃO ATRASADA','diagnosis.ai':'IA SEM CONTEXTO','common.firstVector':'PRIMEIRO VETOR',
      'solutions.kicker':'03 / SOLUÇÕES','solutions.a':'Quatro capacidades.','solutions.b':'Um sistema.','solutions.copy':'A tecnologia muda conforme o gargalo — não o contrário.',
      'architecture.kicker':'04 / ARQUITETURA','architecture.a':'Como o valor','architecture.b':'flui.','architecture.copy':'A menor arquitetura que conecta origem, ação e ROI.','architecture.roi':'tempo · custo · capacidade','architecture.security':'SEGURANÇA','architecture.observe':'OBSERVABILIDADE','architecture.governance':'GOVERNANÇA','architecture.tests':'TESTES',
      'growth.kicker':'05 / GROWTH SYSTEMS','growth.a':'Da mídia ao caixa.','growth.b':'Um único sistema.','growth.copy':'Você investe para trazer atenção. Nós seguimos o caminho até a receita.','growth.lens':'LENTE ATIVA',
      'method.kicker':'06 / MÉTODO','method.a':'Primeiro o impacto.','method.b':'Depois a tecnologia.','method.copy':'Quatro passos para sair do gargalo e chegar em produção.','method.step1':'Diagnóstico','method.step2':'Desenho','method.step3':'Implementação','method.step4':'Otimização',
      'proof.kicker':'07 / ENGENHARIA COM PROVA','proof.a':'Escala real.','proof.b':'Menos esforço. Mais capacidade.','proof.copy':'Experiência técnica aplicada em produção.','proof.m1':'PROCESSADOS / MÊS','proof.m2':'FLUXOS AUTOMATIZADOS','proof.m3':'ESFORÇO MANUAL','proof.m4':'EFICIÊNCIA OPERACIONAL','proof.lens':'LEITURA DE NEGÓCIO',
      'ai.kicker':'08 / APPLIED AI','ai.a':'IA do dado','ai.b':'ao deploy.','ai.copy':'Modelo é só uma peça. Valor nasce do sistema.',
      'final.kicker':'09 / DISCOVERY','final.a':'Qual gargalo merece ser','final.b':'removido primeiro?','final.copy':'Traga o problema em linguagem de negócio. A arquitetura vem depois.','final.opt1':'Processo manual','final.opt2':'Dados dispersos','final.opt3':'Decisão atrasada','final.opt4':'IA sem caso de uso','final.opt5':'Operação sem escala','final.select':'SELECIONE UM GARGALO','final.result':'Encontramos o primeiro vetor de ganho.','final.resultCopy':'Vamos medir tempo, custo, risco e capacidade antes de propor arquitetura.','final.cta':'Abrir diagnóstico'
    },
    en:{
      'hero.kicker':'LIGHTPATH / INTERACTIVE STORY','hero.a':'Your next gain is','hero.b':'hidden in the process.','hero.copy':'From click to cash. Data to decision. Routine to system. AI to product.','hero.cta':'Start',
      'impact.kicker':'01 / IMPACT','impact.a':'Technology is not the product.','impact.b':'Impact is.','impact.copy':'Choose the outcome that needs to move.','impact.core':'IMPACT','impact.sub':'measurable','impact.cost':'REDUCE COST','impact.speed':'ACCELERATE DECISIONS','impact.scale':'CREATE SCALE',
      'diagnosis.kicker':'02 / DIAGNOSIS','diagnosis.a':'Where does value','diagnosis.b':'get stuck?','diagnosis.copy':'Choose the bottleneck. We show the first attack vector.','diagnosis.data':'SCATTERED DATA','diagnosis.manual':'MANUAL PROCESS','diagnosis.delay':'DELAYED DECISION','diagnosis.ai':'AI WITHOUT CONTEXT','common.firstVector':'FIRST VECTOR',
      'solutions.kicker':'03 / SOLUTIONS','solutions.a':'Four capabilities.','solutions.b':'One system.','solutions.copy':'Technology changes with the bottleneck — not the other way around.',
      'architecture.kicker':'04 / ARCHITECTURE','architecture.a':'How value','architecture.b':'flows.','architecture.copy':'The smallest architecture that connects source, action and ROI.','architecture.roi':'time · cost · capacity','architecture.security':'SECURITY','architecture.observe':'OBSERVABILITY','architecture.governance':'GOVERNANCE','architecture.tests':'TESTS',
      'growth.kicker':'05 / GROWTH SYSTEMS','growth.a':'From media to cash.','growth.b':'One system.','growth.copy':'You invest to create attention. We follow the path all the way to revenue.','growth.lens':'ACTIVE LENS',
      'method.kicker':'06 / METHOD','method.a':'Impact first.','method.b':'Technology second.','method.copy':'Four steps from bottleneck to production.','method.step1':'Diagnosis','method.step2':'Design','method.step3':'Implementation','method.step4':'Optimization',
      'proof.kicker':'07 / ENGINEERING WITH PROOF','proof.a':'Real scale.','proof.b':'Less effort. More capacity.','proof.copy':'Technical experience applied in production.','proof.m1':'PROCESSED / MONTH','proof.m2':'AUTOMATED FLOWS','proof.m3':'MANUAL EFFORT','proof.m4':'OPERATIONAL EFFICIENCY','proof.lens':'BUSINESS VIEW',
      'ai.kicker':'08 / APPLIED AI','ai.a':'AI from data','ai.b':'to deployment.','ai.copy':'The model is only one piece. Value comes from the system.',
      'final.kicker':'09 / DISCOVERY','final.a':'Which bottleneck should be','final.b':'removed first?','final.copy':'Bring the problem in business language. Architecture comes after.','final.opt1':'Manual process','final.opt2':'Scattered data','final.opt3':'Delayed decision','final.opt4':'AI without a use case','final.opt5':'Operation without scale','final.select':'SELECT A BOTTLENECK','final.result':'We found the first gain vector.','final.resultCopy':'We measure time, cost, risk and capacity before proposing architecture.','final.cta':'Open diagnosis'
    }
  };
  let current=localStorage.getItem(KEY)==='en'?'en':'pt';
  const t=k=>(D[current]&&D[current][k])||D.pt[k]||k;
  const apply=next=>{current=next==='en'?'en':'pt';localStorage.setItem(KEY,current);document.documentElement.lang=current==='en'?'en':'pt-BR';document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(D[current][k])el.textContent=D[current][k]});document.title=current==='en'?'Interactive Presentation — LightPath Tecnologia':'Apresentação Interativa — LightPath Tecnologia';const meta=document.querySelector('meta[name="description"]');if(meta)meta.content=current==='en'?'Interactive LightPath Tecnologia presentation: Data, AI, Automation and Growth Systems focused on business impact.':'Apresentação interativa da LightPath Tecnologia: dados, IA, automação e Growth Systems orientados a impacto.';window.LIGHTPATH_LANGUAGE=current;toggle?.classList.toggle('is-en',current==='en');toggle?.setAttribute('aria-pressed',String(current==='en'));toggle?.setAttribute('aria-label',current==='en'?'Mudar para português':'Switch to English');window.dispatchEvent(new CustomEvent('lightpath:languagechange',{detail:{lang:current}}))};
  let toggle=document.querySelector('.lp-language-toggle');
  if(!toggle){toggle=document.createElement('button');toggle.type='button';toggle.className='lp-language-toggle';toggle.innerHTML='<span class="lp-lang-label lp-lang-pt">PT</span><span class="lp-lang-track" aria-hidden="true"><i></i></span><span class="lp-lang-label lp-lang-en">EN</span>';document.querySelector('.appbar')?.appendChild(toggle)}
  toggle.addEventListener('click',()=>apply(current==='pt'?'en':'pt'));
  window.LightPathPresentationI18n={t:()=>t,apply,get lang(){return current}};
  apply(current);
})();