(() => {
  'use strict';
  const root=document.getElementById('story'); if(!root)return;
  const scenes=[...document.querySelectorAll('.scene')],prev=document.getElementById('prev-scene'),next=document.getElementById('next-scene'),bar=document.getElementById('story-progress-bar'),num=document.getElementById('scene-number'),dotsRoot=document.getElementById('scene-dots');
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  let current=0,transitioning=false,touchX=0,touchY=0;
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const lang=()=>window.LIGHTPATH_LANGUAGE||(localStorage.getItem('lightpath-language')==='en'?'en':'pt');
  const L=(pt,en)=>lang()==='en'?en:pt;

  const syncViewport=()=>{const v=window.visualViewport;document.documentElement.style.setProperty('--vh',`${Math.round(v?v.height:innerHeight)}px`)};
  syncViewport(); addEventListener('resize',syncViewport,{passive:true}); visualViewport?.addEventListener('resize',syncViewport,{passive:true});

  const dots=scenes.map((_,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',`Cena ${i+1}`);b.addEventListener('click',()=>goTo(i));dotsRoot?.appendChild(b);return b});
  const chrome=()=>{if(num)num.textContent=String(current+1).padStart(2,'0');if(bar)bar.style.transform=`scaleX(${(current+1)/scenes.length})`;if(prev)prev.disabled=current===0;if(next)next.disabled=current===scenes.length-1;dots.forEach((d,i)=>d.classList.toggle('is-active',i===current))};

  const animateEntry=scene=>{if(reduced||!window.gsap)return;const items=[...scene.querySelector('.scene-inner')?.children||[]];gsap.killTweensOf(items);gsap.fromTo(items,{opacity:0,y:14},{opacity:1,y:0,duration:.48,stagger:.055,ease:'power3.out',clearProps:'transform'});const vectors=scene.querySelectorAll('.hero-vector .vector');if(vectors.length){gsap.set(vectors,{strokeDashoffset:500});gsap.to(vectors,{strokeDashoffset:0,duration:1.1,stagger:.12,ease:'power2.inOut'})}scene.querySelectorAll('[data-count]').forEach(el=>{const target=Number(el.dataset.count||0),prefix=el.dataset.prefix||'',suffix=el.dataset.suffix||'';const s={v:0};gsap.to(s,{v:target,duration:.9,ease:'power3.out',onUpdate:()=>el.textContent=`${prefix}${Math.round(s.v)}${suffix}`,onComplete:()=>el.textContent=`${prefix}${target}${suffix}`})})};

  function goTo(target){target=clamp(target,0,scenes.length-1);if(target===current||transitioning)return false;const from=current,out=scenes[from],inc=scenes[target],dir=target>from?1:-1;transitioning=true;current=target;chrome();inc.classList.add('is-active');inc.setAttribute('aria-hidden','false');
    if(reduced||!window.gsap){out.classList.remove('is-active');out.setAttribute('aria-hidden','true');animateEntry(inc);transitioning=false;return true}
    gsap.killTweensOf([out,inc]);gsap.set(inc,{xPercent:dir*100,opacity:.3,visibility:'visible'});gsap.set(out,{xPercent:0,opacity:1,visibility:'visible'});gsap.timeline({onComplete:()=>{out.classList.remove('is-active');out.setAttribute('aria-hidden','true');scenes.forEach((s,i)=>{if(i!==current)s.classList.remove('is-active')});gsap.set([out,inc],{clearProps:'transform,opacity,visibility'});animateEntry(inc);transitioning=false}}).to(out,{xPercent:-dir*22,opacity:0,duration:.38,ease:'power3.inOut'},0).to(inc,{xPercent:0,opacity:1,duration:.48,ease:'power4.out'},.02);return true}
  const goNext=()=>goTo(current+1),goPrev=()=>goTo(current-1);next?.addEventListener('click',goNext);prev?.addEventListener('click',goPrev);document.querySelectorAll('.js-next').forEach(b=>b.addEventListener('click',goNext));

  /* One physical wheel/trackpad gesture = one scene. No second wheel controller. */
  let wheelLocked=false,wheelSum=0,wheelDir=0,wheelIdle=null;
  const resetWheel=()=>{wheelLocked=false;wheelSum=0;wheelDir=0};
  const norm=e=>{let d=Math.abs(e.deltaY)>=Math.abs(e.deltaX)?e.deltaY:e.deltaX;if(e.deltaMode===1)d*=16;if(e.deltaMode===2)d*=Math.max(innerHeight,1);return d};
  addEventListener('wheel',e=>{if(e.ctrlKey)return;e.preventDefault();const d=norm(e);if(Math.abs(d)<.55)return;clearTimeout(wheelIdle);wheelIdle=setTimeout(resetWheel,125);if(transitioning){wheelLocked=true;return}if(wheelLocked)return;const dir=Math.sign(d);if(wheelDir&&dir!==wheelDir)wheelSum=0;wheelDir=dir;wheelSum+=d;if(Math.abs(wheelSum)<32)return;wheelLocked=true;wheelSum=0;dir>0?goNext():goPrev()},{capture:true,passive:false});

  addEventListener('keydown',e=>{const t=e.target?.tagName?.toLowerCase();if(['input','textarea','select'].includes(t))return;if(['ArrowRight','ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();goNext()}else if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();goPrev()}else if(e.key==='Home')goTo(0);else if(e.key==='End')goTo(scenes.length-1)});
  root.addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchX=t.clientX;touchY=t.clientY},{passive:true});root.addEventListener('touchmove',e=>e.preventDefault(),{passive:false});root.addEventListener('touchend',e=>{if(transitioning)return;const t=e.changedTouches[0],dx=t.clientX-touchX,dy=t.clientY-touchY;if(Math.max(Math.abs(dx),Math.abs(dy))<42)return;(Math.abs(dx)>=Math.abs(dy)?dx:dy)<0?goNext():goPrev()},{passive:true});

  const impact={custo:{pt:['MENOS CUSTO','menos handoffs · retrabalho · operação manual'],en:['LOWER COST','fewer handoffs · rework · manual work']},decisao:{pt:['MAIS VELOCIDADE','dado confiável no momento da decisão'],en:['MORE SPEED','trusted data at the moment of decision']},escala:{pt:['MAIS ESCALA','crescimento sem multiplicar esforço humano'],en:['MORE SCALE','growth without multiplying human effort']}};
  const renderImpact=key=>{const d=impact[key][lang()];document.getElementById('impact-core-title').textContent=d[0];document.getElementById('impact-core-sub').textContent=d[1]};document.querySelectorAll('[data-impact]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-impact]').forEach(x=>x.classList.toggle('is-selected',x===b));renderImpact(b.dataset.impact)}));

  const bottleneck={dados:{pt:['DATA FOUNDATION','Integrar fontes, criar contratos e tornar o dado confiável antes de acelerar analytics ou IA.','Métrica → latência + qualidade'],en:['DATA FOUNDATION','Integrate sources, create contracts and make data reliable before accelerating analytics or AI.','Metric → latency + quality']},processo:{pt:['AUTOMATION LAYER','Remover passos repetitivos e conectar eventos, integrações e observabilidade.','Métrica → horas + retrabalho'],en:['AUTOMATION LAYER','Remove repetitive steps and connect events, integrations and observability.','Metric → hours + rework']},decisao:{pt:['DECISION LAYER','Levar indicador, alerta ou modelo até o ponto em que a decisão acontece.','Métrica → tempo de decisão + acurácia'],en:['DECISION LAYER','Bring an indicator, alert or model to the exact point where the decision happens.','Metric → decision time + accuracy']},ia:{pt:['AI OPERATIONS','Conectar modelo a contexto, ferramentas, guardrails e uma métrica de valor.','Métrica → tarefa resolvida + qualidade'],en:['AI OPERATIONS','Connect the model to context, tools, guardrails and a value metric.','Metric → task solved + quality']}};
  const renderBottleneck=key=>{const d=bottleneck[key][lang()];document.getElementById('bottleneck-solution').textContent=d[0];document.getElementById('bottleneck-copy').textContent=d[1];document.getElementById('bottleneck-metric').textContent=d[2]};document.querySelectorAll('[data-bottleneck]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-bottleneck]').forEach(x=>x.classList.toggle('is-selected',x===b));renderBottleneck(b.dataset.bottleneck)}));

  const solution={data:{pt:['DATA / 01','Data Platform','Base confiável para decidir, automatizar e escalar.','Pipelines · lakehouse · qualidade · observabilidade'],en:['DATA / 01','Data Platform','A reliable foundation to decide, automate and scale.','Pipelines · lakehouse · quality · observability']},ai:{pt:['AI / 02','AI Operations','IA conectada ao contexto e ao trabalho real da empresa.','RAG · agentes · copilots · avaliação'],en:['AI / 02','AI Operations','AI connected to the company context and real work.','RAG · agents · copilots · evaluation']},automation:{pt:['AUTO / 03','Automation','Processos que deixam de depender de memória e acompanhamento.','APIs · webhooks · eventos · filas · alertas'],en:['AUTO / 03','Automation','Processes that stop depending on memory and follow-up.','APIs · webhooks · events · queues · alerts']},analytics:{pt:['DECISION / 04','Analytics & DS','Dados que apontam o próximo movimento da operação.','KPIs · BI · forecast · segmentação · otimização'],en:['DECISION / 04','Analytics & DS','Data that points to the next operational move.','KPIs · BI · forecast · segmentation · optimization']}};
  const renderSolution=key=>{const d=solution[key][lang()];['solution-code','solution-title','solution-copy','solution-stack'].forEach((id,i)=>document.getElementById(id).textContent=d[i])};document.querySelectorAll('[data-solution]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-solution]').forEach(x=>x.classList.toggle('is-selected',x===b));renderSolution(b.dataset.solution)}));

  document.querySelectorAll('[data-arch]').forEach((b,i)=>b.addEventListener('click',()=>document.querySelectorAll('[data-arch]').forEach((x,j)=>x.classList.toggle('is-live',j<=i))));

  const growth={media:{pt:['Aquisição com feedback de negócio.','Criativo e mídia precisam ser avaliados até o pedido real — não só pelo clique.','Decisão → CAC · receita · qualidade do tráfego'],en:['Acquisition with business feedback.','Creative and media should be evaluated through the real order — not only the click.','Decision → CAC · revenue · traffic quality']},landing:{pt:['Conversão tratada como sistema.','Mensagem, UX, quiz e roteamento são medidos por avanço real no funil.','Decisão → visita · intenção · abandono'],en:['Conversion treated as a system.','Message, UX, quiz and routing are measured by real funnel progression.','Decision → visit · intent · abandonment']},checkout:{pt:['Checkout como infraestrutura de receita.','Oferta, pagamento e recovery precisam funcionar juntos e continuar rastreáveis.','Decisão → checkout · aprovação · perda'],en:['Checkout as revenue infrastructure.','Offer, payment and recovery must work together and remain traceable.','Decision → checkout · approval · loss']},order:{pt:['Uma verdade comercial confiável.','Pedido e pagamento são reconciliados com sessão, campanha e eventos.','Decisão → compra real · deduplicação · atribuição'],en:['A reliable commercial truth.','Order and payment are reconciled with session, campaign and events.','Decision → real purchase · deduplication · attribution']},lifecycle:{pt:['Receita continua depois da compra.','Entrega, CRM e lifecycle fecham o loop entre aquisição, experiência e retenção.','Decisão → ativação · retenção · LTV'],en:['Revenue continues after purchase.','Delivery, CRM and lifecycle close the loop between acquisition, experience and retention.','Decision → activation · retention · LTV']}};
  const renderGrowth=key=>{const d=growth[key][lang()];document.getElementById('growth-insight-title').textContent=d[0];document.getElementById('growth-insight-copy').textContent=d[1];document.getElementById('growth-insight-kpi').textContent=d[2]};document.querySelectorAll('[data-growth-step]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-growth-step]').forEach(x=>x.classList.toggle('is-selected',x===b));renderGrowth(b.dataset.growthStep)}));

  const method=[{pt:['DIAGNÓSTICO','Mapeamos onde o valor está travado.','Mapa de oportunidades priorizado'],en:['DIAGNOSIS','We map where value is stuck.','Prioritized opportunity map']},{pt:['DESENHO','Escolhemos a menor arquitetura que resolve.','Architecture + plano de execução'],en:['DESIGN','We choose the smallest architecture that solves it.','Architecture + execution plan']},{pt:['IMPLEMENTAÇÃO','Construímos para uso real, não para demo.','Solução em produção'],en:['IMPLEMENTATION','We build for real use, not for a demo.','Solution in production']},{pt:['OTIMIZAÇÃO','Medimos o que mudou e ampliamos o ganho.','ROI operacional + próximos ganhos'],en:['OPTIMIZATION','We measure what changed and expand the gain.','Operational ROI + next gains']}];
  const renderMethod=i=>{const d=method[i][lang()];document.getElementById('method-tag').textContent=d[0];document.getElementById('method-title').textContent=d[1];document.getElementById('method-output').textContent=d[2]};document.querySelectorAll('[data-method]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-method]').forEach(x=>x.classList.toggle('is-selected',x===b));renderMethod(Number(b.dataset.method))}));

  const proof={scale:{pt:['Capacidade para crescer sem linearizar infraestrutura.','Pipelines distribuídos e runtime otimizado transformam volume em capacidade previsível.'],en:['Capacity to grow without linear infrastructure growth.','Distributed pipelines and optimized runtime turn volume into predictable capacity.']},auto:{pt:['Rotina deixa de consumir atenção humana.','Orquestração recorrente reduz intervenção, dependência de memória e risco.'],en:['Routine stops consuming human attention.','Recurring orchestration reduces intervention, memory dependency and risk.']},manual:{pt:['Software absorve trabalho antes feito por pessoas.','Serviços de ingestão substituem coleta e movimentação manual.'],en:['Software absorbs work previously done by people.','Ingestion services replace manual collection and movement.']},ops:{pt:['Informação chega mais perto da decisão.','SQL, BI e automação reduzem latência operacional e aumentam previsibilidade.'],en:['Information gets closer to the decision.','SQL, BI and automation reduce operational latency and increase predictability.']}};
  const renderProof=key=>{const d=proof[key][lang()];document.getElementById('proof-title').textContent=d[0];document.getElementById('proof-copy').textContent=d[1]};document.querySelectorAll('[data-proof]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-proof]').forEach(x=>x.classList.toggle('is-selected',x===b));renderProof(b.dataset.proof)}));

  const ai={pt:['Contexto entra. A análise começa com dados estruturados.','O modelo executa dentro de um fluxo controlado — não isolado.','A saída vira contrato estruturado para software e operação.','Eventos e outcomes fecham o loop para medir qualidade e valor.'],en:['Context enters. Analysis starts with structured data.','The model runs inside a controlled flow — not in isolation.','The output becomes a structured contract for software and operations.','Events and outcomes close the loop to measure quality and value.']};
  let aiIndex=0;const renderAI=i=>{aiIndex=i;document.getElementById('ai-message').textContent=ai[lang()][i];document.querySelectorAll('[data-ai-step]').forEach((x,j)=>x.classList.toggle('is-active',j<=i))};document.querySelectorAll('[data-ai-step]').forEach(b=>b.addEventListener('click',()=>renderAI(Number(b.dataset.aiStep))));

  const diagnostic={manual:{pt:['AUTOMATION FIRST','Mapear passos, horas e handoffs. Automatizar o trecho recorrente com menor risco.','Medir → horas recuperadas · retrabalho · SLA'],en:['AUTOMATION FIRST','Map steps, hours and handoffs. Automate the recurring, lower-risk segment first.','Measure → recovered hours · rework · SLA']},data:{pt:['DATA FOUNDATION FIRST','Criar uma camada confiável antes de multiplicar dashboards ou IA.','Medir → latência · qualidade · disponibilidade'],en:['DATA FOUNDATION FIRST','Create a reliable layer before multiplying dashboards or AI.','Measure → latency · quality · availability']},decision:{pt:['DECISION LAYER FIRST','Levar informação, alerta ou modelo até a decisão que hoje acontece tarde.','Medir → lead time · acurácia · perda evitada'],en:['DECISION LAYER FIRST','Bring information, alerts or models to the decision that happens too late today.','Measure → lead time · accuracy · avoided loss']},ai:{pt:['USE CASE FIRST','Escolher uma tarefa real, definir baseline e provar valor antes de ampliar IA.','Medir → tarefa resolvida · qualidade · custo'],en:['USE CASE FIRST','Choose a real task, define a baseline and prove value before expanding AI.','Measure → task solved · quality · cost']},scale:{pt:['ARCHITECTURE FIRST','Encontrar o componente que cresce linearmente com pessoas, volume ou custo.','Medir → throughput · custo marginal · capacidade'],en:['ARCHITECTURE FIRST','Find the component that grows linearly with people, volume or cost.','Measure → throughput · marginal cost · capacity']}};
  let diagnosticKey=null;const renderDiagnostic=key=>{if(!key)return;diagnosticKey=key;const d=diagnostic[key][lang()],r=document.getElementById('diagnostic-result');r.innerHTML=`<small>${d[0]}</small><strong>${d[1]}</strong><p>${d[2]}</p>`};document.querySelectorAll('[data-diagnostic]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-diagnostic]').forEach(x=>x.classList.toggle('is-selected',x===b));renderDiagnostic(b.dataset.diagnostic)}));

  addEventListener('lightpath:languagechange',()=>{const a=document.querySelector('[data-impact].is-selected');if(a)renderImpact(a.dataset.impact);const b=document.querySelector('[data-bottleneck].is-selected');if(b)renderBottleneck(b.dataset.bottleneck);const s=document.querySelector('[data-solution].is-selected');if(s)renderSolution(s.dataset.solution);const g=document.querySelector('[data-growth-step].is-selected');if(g)renderGrowth(g.dataset.growthStep);const m=document.querySelector('[data-method].is-selected');if(m)renderMethod(Number(m.dataset.method));const p=document.querySelector('[data-proof].is-selected');if(p)renderProof(p.dataset.proof);renderAI(aiIndex);if(diagnosticKey)renderDiagnostic(diagnosticKey)});

  const setupField=()=>{if(reduced)return;const canvas=document.getElementById('vector-field'),ctx=canvas?.getContext('2d',{alpha:true});if(!ctx)return;let w=0,h=0,dpr=1,last=0;const traces=[];const mobile=()=>innerWidth<760;const resize=()=>{const v=visualViewport;w=v?v.width:innerWidth;h=v?v.height:innerHeight;dpr=Math.min(mobile()?1:1.2,devicePixelRatio||1);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;ctx.setTransform(dpr,0,0,dpr,0,0);traces.length=0;for(let i=0;i<(mobile()?10:24);i++)traces.push({x:Math.random()*w,y:Math.random()*h,s:.35+Math.random()*.6,a:Math.random()*6})};const draw=t=>{requestAnimationFrame(draw);if(document.hidden||t-last<(mobile()?48:24))return;last=t;ctx.clearRect(0,0,w,h);traces.forEach((p,i)=>{const ox=p.x,oy=p.y,ang=-.92+Math.sin(p.x*.006+t*.00035+p.a)*.22;p.x+=Math.cos(ang)*p.s;p.y+=Math.sin(ang)*p.s;ctx.beginPath();ctx.moveTo(ox,oy);ctx.lineTo(p.x,p.y);ctx.strokeStyle=`rgba(${i%4===0?'183,255,55':'112,244,208'},${mobile()?.05:.085})`;ctx.lineWidth=.65;ctx.stroke();if(p.y<-30||p.x>w+40||p.x<-40){p.x=Math.random()*w;p.y=h+30}})};resize();addEventListener('resize',resize,{passive:true});visualViewport?.addEventListener('resize',resize,{passive:true});requestAnimationFrame(draw)};

  scenes.forEach((s,i)=>s.setAttribute('aria-hidden',i?'true':'false'));chrome();animateEntry(scenes[0]);setupField();root.focus({preventScroll:true});
})();